{% set name = "boost_mp11" %}
{% set version = "1.76.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/boostorg/mp11/
  git_rev: boost-1.76.0
  patches:
    - 0001-Disabled-tests.patch

build:
  number: 2

requirements:
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                     # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}               # [x86_64 and c_compiler_version == "7.2.*"]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                     # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}               # [x86_64 and c_compiler_version == "7.2.*"]
  run_constrained:
    # Cannot be installed at the same time as boost-cpp as it clobbers the mp11 headers
    - boost-cpp <0a0

test:
  commands:
    - test -f $PREFIX/include/boost/mp11.hpp  # [linux]

about:
  home: https://github.com/boostorg/mp11
  summary: C++11 metaprogramming library
  license: BSL-1.0
  license_file: LICENSE_1_0.txt

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
